# Generated by Django 4.0.5 on 2022-06-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_listing_image_4_listing_image_5_listing_image_6_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('1', '1'), ('7', '7'), ('9', '9'), ('2', '2'), ('5', '5'), ('10', '10'), ('8', '8'), ('3', '3'), ('4', '4'), ('6', '6')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(choices=[('400000', '$400,000'), ('800000', '$800,000'), ('100000', '$100,000'), ('600000', '$600,000'), ('1000000', '$1M+'), ('500000', '$500,000'), ('300000', '$300,000'), ('900000', '$900,000'), ('700000', '$700,000'), ('200000', '$200,000')]),
        ),
    ]
