# Generated by Django 4.0.5 on 2022-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_alter_listing_bedrooms_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('5', '5'), ('', 'Choose'), ('2', '2'), ('6', '6'), ('4', '4'), ('10', '10'), ('8', '8'), ('1', '1'), ('9', '9'), ('7', '7'), ('3', '3')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(choices=[('900000', '$900,000'), ('500000', '$500,000'), ('', 'Choose'), ('300000', '$300,000'), ('1000000', '$1M+'), ('200000', '$200,000'), ('700000', '$700,000'), ('100000', '$100,000'), ('600000', '$600,000'), ('400000', '$400,000'), ('800000', '$800,000')]),
        ),
    ]
