# Generated by Django 4.0.5 on 2022-06-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_alter_listing_bedrooms_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('8', '8'), ('9', '9'), ('5', '5'), ('4', '4'), ('3', '3'), ('10', '10'), ('1', '1'), ('7', '7'), ('6', '6'), ('2', '2')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(choices=[('500,000', '$500,000'), ('800,000', '$800,000'), ('900,000', '$900,000'), ('700,000', '$700,000'), ('300,000', '$300,000'), ('400,000', '$400,000'), ('100,000', '$100,000'), ('1,000,000', '$1M+'), ('600,000', '$600,000'), ('200,000', '$200,000')]),
        ),
    ]
