# Generated by Django 4.0.5 on 2022-06-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_alter_listing_bedrooms_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('9', '9'), ('8', '8'), ('4', '4'), ('5', '5'), ('3', '3'), ('1', '1'), ('6', '6'), ('7', '7'), ('2', '2'), ('10', '10')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(choices=[('100,000', '$100,000'), ('200,000', '$200,000')]),
        ),
    ]
