# Generated by Django 4.0.5 on 2022-06-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0008_alter_listing_bedrooms_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(choices=[('100000', '$100,000'), ('200000', '$200,000'), ('300000', '$300,000'), ('400000', '$400,000'), ('500000', '$500,000'), ('700000', '$700,000'), ('600000', '$600,000'), ('800000', '$800,000'), ('900000', '$900,000'), ('1000000', '$1M+')]),
        ),
    ]
