# Generated by Django 4.0.5 on 2022-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0011_alter_listing_bedrooms_alter_listing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
